import { Departement } from '@/archives/departements/Departement.js';
import { DATASETS_IDS } from '@/archives/url/DATASETS_IDS.js';
import { getURLs } from '@/archives/url/getURLs.js';
import { fetchMetadata } from '@/archives/url/metadata/fetchMetadata.meteo-data.js';

import { describe, expect, it } from 'vitest';

describe('getURLs', () => {
    it('should fetch metadata for this dataset, page, pageSize and departement, and extract URLs', async () => {
        const urls = await getURLs({
            datasetId: DATASETS_IDS.infrahoraire,
            fetchMetadata,
            page: 1,
            pageSize: 2,
            departements: [Departement.of(1)],
        });
        expect(urls).toEqual([
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_01_2000-2009.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_01_2010-2019.csv.gz',
        ]);
    });
    it('should fetch metadata for 2 departements, and extract URLs', async () => {
        const urls = await getURLs({
            datasetId: DATASETS_IDS.infrahoraire,
            fetchMetadata,
            departements: [Departement.of(29), Departement.of(76)],
        });
        expect(urls).toEqual([
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_29_2000-2009.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_29_2010-2019.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_29_previous-2020-2023.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_29_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_76_2000-2009.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_76_2010-2019.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_76_previous-2020-2023.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_76_latest-2024-2025.csv.gz',
        ]);
    });
    it('should fetch metadata for the latest files, and extract URLs', async () => {
        const urls = await getURLs({
            datasetId: DATASETS_IDS.infrahoraire,
            fetchMetadata,
            latest: true,
        });
        expect(urls).toEqual([
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_01_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_02_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_03_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_04_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_05_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_06_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_07_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_08_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_09_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_10_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_11_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_12_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_13_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_14_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_15_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_16_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_17_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_18_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_19_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_20_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_21_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_22_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_23_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_24_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_25_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_26_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_27_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_28_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_29_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_30_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_31_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_32_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_33_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_34_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_35_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_36_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_37_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_38_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_39_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_40_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_41_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_42_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_43_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_44_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_45_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_46_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_47_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_48_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_49_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_50_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_51_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_52_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_53_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_54_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_55_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_56_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_57_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_58_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_59_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_60_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_61_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_62_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_63_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_64_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_65_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_66_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_67_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_68_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_69_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_70_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_71_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_72_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_73_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_74_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_75_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_76_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_77_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_78_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_79_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_80_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_81_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_82_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_83_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_84_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_85_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_86_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_87_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_88_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_89_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_90_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_91_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_92_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_93_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_94_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_95_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_971_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_972_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_973_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_974_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_975_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_984_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_985_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_986_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_987_latest-2024-2025.csv.gz',
            'https://object.files.data.gouv.fr/meteofrance/data/synchro_ftp/BASE/MIN/MN_988_latest-2024-2025.csv.gz',
        ]);
    });
});
