-- CreateTable
CREATE TABLE "InfrahoraireTempsReel"
(
    "geo_id_insee"   CHAR(8)          NOT NULL,
    "lat"            DOUBLE PRECISION NOT NULL,
    "lon"            DOUBLE PRECISION NOT NULL,
    "reference_time" TIMESTAMP(3)     NOT NULL,
    "insert_time"    TIMESTAMP(3)     NOT NULL,
    "validity_time"  TIMESTAMP(3)     NOT NULL,
    "t"              DOUBLE PRECISION,
    "td"             DOUBLE PRECISION,
    "u"              INTEGER,
    "dd"             INTEGER,
    "ff"             DOUBLE PRECISION,
    "dxi10"          INTEGER,
    "fxi10"          DOUBLE PRECISION,
    "rr_per"         DOUBLE PRECISION,
    "t_10"           DOUBLE PRECISION,
    "t_20"           DOUBLE PRECISION,
    "t_50"           DOUBLE PRECISION,
    "t_100"          DOUBLE PRECISION,
    "vv"             INTEGER,
    "etat_sol"       INTEGER,
    "sss"            DOUBLE PRECISION,
    "n"              INTEGER,
    "insolh"         DOUBLE PRECISION,
    "ray_glo01"      DOUBLE PRECISION,
    "pres"           DOUBLE PRECISION,
    "pmer"           DOUBLE PRECISION,

    CONSTRAINT "InfrahoraireTempsReel_pkey" PRIMARY KEY ("geo_id_insee", "validity_time")
);

-- CreateTable
CREATE TABLE "HoraireTempsReel"
(
    "geo_id_insee"   CHAR(8)          NOT NULL,
    "lat"            DOUBLE PRECISION NOT NULL,
    "lon"            DOUBLE PRECISION NOT NULL,
    "reference_time" TIMESTAMP(3)     NOT NULL,
    "insert_time"    TIMESTAMP(3)     NOT NULL,
    "validity_time"  TIMESTAMP(3)     NOT NULL,
    "t"              DOUBLE PRECISION,
    "td"             DOUBLE PRECISION,
    "tx"             DOUBLE PRECISION,
    "tn"             DOUBLE PRECISION,
    "u"              INTEGER,
    "ux"             INTEGER,
    "un"             INTEGER,
    "dd"             INTEGER,
    "ff"             DOUBLE PRECISION,
    "dxy"            INTEGER,
    "fxy"            DOUBLE PRECISION,
    "dxi"            INTEGER,
    "fxi"            DOUBLE PRECISION,
    "rr1"            DOUBLE PRECISION,
    "t_10"           DOUBLE PRECISION,
    "t_20"           DOUBLE PRECISION,
    "t_50"           DOUBLE PRECISION,
    "t_100"          DOUBLE PRECISION,
    "vv"             INTEGER,
    "etat_sol"       INTEGER,
    "sss"            DOUBLE PRECISION,
    "n"              INTEGER,
    "insolh"         DOUBLE PRECISION,
    "ray_glo01"      DOUBLE PRECISION,
    "pres"           DOUBLE PRECISION,
    "pmer"           DOUBLE PRECISION,

    CONSTRAINT "HoraireTempsReel_pkey" PRIMARY KEY ("geo_id_insee", "validity_time")
);
