import { InMemoryQuotidiennesRepository } from '@/db/quotidiennes/InMemoryRepository.js';
import { createInMemoryGlobber } from '@/lib/fs/glob/glob.in-memory.js';
import { createInMemoryLineReader } from '@/lib/fs/read-lines/readLines.in-memory.js';
import { getArrayFromAsyncGenerator } from '@/lib/generator/generatorUtils.js';
import { saveCSVsToDB } from '@/quotidiennes/use-cases/saveCSVsToDB.js';
import { assert, describe, it } from 'vitest';

describe('saveCSVsToDB', () => {
    it('should work', async () => {
        const repository = new InMemoryQuotidiennesRepository();
        await saveCSVsToDB({
            directory: '/my/directory',
            globber: createInMemoryGlobber([
                '/my/directory/Q_01_previous-1950-2022.csv',
                '/my/directory/Q_01_latest-2023-2024.csv',
            ]),
            lineReader: createInMemoryLineReader({
                '/my/directory/Q_01_previous-1950-2022.csv': [
                    'NUM_POSTE;NOM_USUEL;LAT;LON;ALTI;AAAAMMJJ;DHUMEC;QDHUMEC;PMERM;QPMERM;PMERMIN;QPMERMIN;INST;QINST;GLOT;QGLOT;DIFT;QDIFT;DIRT;QDIRT;INFRART;QINFRART;UV;QUV;UV_INDICEX;QUV_INDICEX;SIGMA;QSIGMA;UN;QUN;HUN;QHUN;UX;QUX;HUX;QHUX;UM;QUM;DHUMI40;QDHUMI40;DHUMI80;QDHUMI80;TSVM;QTSVM;ETPMON;QETPMON;ETPGRILLE;QETPGRILLE;ECOULEMENTM;QECOULEMENTM;HNEIGEF;QHNEIGEF;NEIGETOTX;QNEIGETOTX;NEIGETOT06;QNEIGETOT06;NEIG;QNEIG;BROU;QBROU;ORAG;QORAG;GRESIL;QGRESIL;GRELE;QGRELE;ROSEE;QROSEE;VERGLAS;QVERGLAS;SOLNEIGE;QSOLNEIGE;GELEE;QGELEE;FUMEE;QFUMEE;BRUME;QBRUME;ECLAIR;QECLAIR;NB300;QNB300;BA300;QBA300;TMERMIN;QTMERMIN;TMERMAX;QTMERMAX',
                    '01089001;AMBERIEU;45.976500;5.329333;250;19350112;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;1;1;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;',
                    '01014002;ARBENT;46.278167;5.669000;534;20230101;;;;;;;;;;;;;;;;;;;;;;;43;1;1944;9;75;1;27;9;55;1;0;9;0;9;8.9;9;;;3.1;9;;;;;0;9;0;9;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;',
                    '',
                ],
                '/my/directory/Q_01_latest-2023-2024.csv': [
                    'NUM_POSTE;NOM_USUEL;LAT;LON;ALTI;AAAAMMJJ;DHUMEC;QDHUMEC;PMERM;QPMERM;PMERMIN;QPMERMIN;INST;QINST;GLOT;QGLOT;DIFT;QDIFT;DIRT;QDIRT;INFRART;QINFRART;UV;QUV;UV_INDICEX;QUV_INDICEX;SIGMA;QSIGMA;UN;QUN;HUN;QHUN;UX;QUX;HUX;QHUX;UM;QUM;DHUMI40;QDHUMI40;DHUMI80;QDHUMI80;TSVM;QTSVM;ETPMON;QETPMON;ETPGRILLE;QETPGRILLE;ECOULEMENTM;QECOULEMENTM;HNEIGEF;QHNEIGEF;NEIGETOTX;QNEIGETOTX;NEIGETOT06;QNEIGETOT06;NEIG;QNEIG;BROU;QBROU;ORAG;QORAG;GRESIL;QGRESIL;GRELE;QGRELE;ROSEE;QROSEE;VERGLAS;QVERGLAS;SOLNEIGE;QSOLNEIGE;GELEE;QGELEE;FUMEE;QFUMEE;BRUME;QBRUME;ECLAIR;QECLAIR;NB300;QNB300;BA300;QBA300;TMERMIN;QTMERMIN;TMERMAX;QTMERMAX',
                    '01014002;ARBENT;46.278167;5.669000;534;20230102;1;9;2.2;9;2.2;9;1;9;1;9;1;9;1;9;1;9;12;9;12;9;100;9;100;9;1230;9;100;9;1230;9;100;9;1;9;1;9;2.2;9;2.2;9;2.2;9;2.2;9;1;9;1;9;1;9;0;9;0;9;0;9;0;9;0;9;0;9;0;9;0;9;0;9;0;9;0;9;0;9;8;9;1;9;-3.3;9;-3.3;9',
                    '01014002;ARBENT;46.278167;5.669000;534;20230103;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;',
                    '',
                ],
            }),
            repository,
        });
        assert.sameDeepMembers(await getArrayFromAsyncGenerator(repository.getAll()), [
            {
                NUM_POSTE: '01089001',
                NOM_USUEL: 'AMBERIEU',
                LAT: 45.9765,
                LON: 5.329333,
                ALTI: 250,
                AAAAMMJJ: new Date('1935-01-12T00:00:00Z'),
                DHUMEC: null,
                QDHUMEC: null,
                PMERM: null,
                QPMERM: null,
                PMERMIN: null,
                QPMERMIN: null,
                INST: null,
                QINST: null,
                GLOT: null,
                QGLOT: null,
                DIFT: null,
                QDIFT: null,
                DIRT: null,
                QDIRT: null,
                INFRART: null,
                QINFRART: null,
                UV: null,
                QUV: null,
                UV_INDICEX: null,
                QUV_INDICEX: null,
                SIGMA: null,
                QSIGMA: null,
                UN: null,
                QUN: null,
                HUN: null,
                QHUN: null,
                UX: null,
                QUX: null,
                HUX: null,
                QHUX: null,
                UM: null,
                QUM: null,
                DHUMI40: null,
                QDHUMI40: null,
                DHUMI80: null,
                QDHUMI80: null,
                TSVM: null,
                QTSVM: null,
                ETPMON: null,
                QETPMON: null,
                ETPGRILLE: null,
                QETPGRILLE: null,
                ECOULEMENTM: null,
                QECOULEMENTM: null,
                HNEIGEF: null,
                QHNEIGEF: null,
                NEIGETOTX: null,
                QNEIGETOTX: null,
                NEIGETOT06: null,
                QNEIGETOT06: null,
                NEIG: true,
                QNEIG: 1,
                BROU: null,
                QBROU: null,
                ORAG: null,
                QORAG: null,
                GRESIL: null,
                QGRESIL: null,
                GRELE: null,
                QGRELE: null,
                ROSEE: null,
                QROSEE: null,
                VERGLAS: null,
                QVERGLAS: null,
                SOLNEIGE: null,
                QSOLNEIGE: null,
                GELEE: null,
                QGELEE: null,
                FUMEE: null,
                QFUMEE: null,
                BRUME: null,
                QBRUME: null,
                ECLAIR: null,
                QECLAIR: null,
                NB300: null,
                QNB300: null,
                BA300: null,
                QBA300: null,
                TMERMIN: null,
                QTMERMIN: null,
                TMERMAX: null,
                QTMERMAX: null,
            },
            {
                NUM_POSTE: '01014002',
                NOM_USUEL: 'ARBENT',
                LAT: 46.278167,
                LON: 5.669,
                ALTI: 534,
                AAAAMMJJ: new Date('2023-01-01T00:00:00Z'),
                DHUMEC: null,
                QDHUMEC: null,
                PMERM: null,
                QPMERM: null,
                PMERMIN: null,
                QPMERMIN: null,
                INST: null,
                QINST: null,
                GLOT: null,
                QGLOT: null,
                DIFT: null,
                QDIFT: null,
                DIRT: null,
                QDIRT: null,
                INFRART: null,
                QINFRART: null,
                UV: null,
                QUV: null,
                UV_INDICEX: null,
                QUV_INDICEX: null,
                SIGMA: null,
                QSIGMA: null,
                UN: 43,
                QUN: 1,
                HUN: '1944',
                QHUN: 9,
                UX: 75,
                QUX: 1,
                HUX: '0027',
                QHUX: 9,
                UM: 55,
                QUM: 1,
                DHUMI40: 0,
                QDHUMI40: 9,
                DHUMI80: 0,
                QDHUMI80: 9,
                TSVM: 8.9,
                QTSVM: 9,
                ETPMON: null,
                QETPMON: null,
                ETPGRILLE: 3.1,
                QETPGRILLE: 9,
                ECOULEMENTM: null,
                QECOULEMENTM: null,
                HNEIGEF: null,
                QHNEIGEF: null,
                NEIGETOTX: 0,
                QNEIGETOTX: 9,
                NEIGETOT06: 0,
                QNEIGETOT06: 9,
                NEIG: null,
                QNEIG: null,
                BROU: null,
                QBROU: null,
                ORAG: null,
                QORAG: null,
                GRESIL: null,
                QGRESIL: null,
                GRELE: null,
                QGRELE: null,
                ROSEE: null,
                QROSEE: null,
                VERGLAS: null,
                QVERGLAS: null,
                SOLNEIGE: null,
                QSOLNEIGE: null,
                GELEE: null,
                QGELEE: null,
                FUMEE: null,
                QFUMEE: null,
                BRUME: null,
                QBRUME: null,
                ECLAIR: null,
                QECLAIR: null,
                NB300: null,
                QNB300: null,
                BA300: null,
                QBA300: null,
                TMERMIN: null,
                QTMERMIN: null,
                TMERMAX: null,
                QTMERMAX: null,
            },
            {
                NUM_POSTE: '01014002',
                NOM_USUEL: 'ARBENT',
                LAT: 46.278167,
                LON: 5.669,
                ALTI: 534,
                AAAAMMJJ: new Date('2023-01-02T00:00:00Z'),
                DHUMEC: 1,
                QDHUMEC: 9,
                PMERM: 2.2,
                QPMERM: 9,
                PMERMIN: 2.2,
                QPMERMIN: 9,
                INST: 1,
                QINST: 9,
                GLOT: 1,
                QGLOT: 9,
                DIFT: 1,
                QDIFT: 9,
                DIRT: 1,
                QDIRT: 9,
                INFRART: 1,
                QINFRART: 9,
                UV: 12,
                QUV: 9,
                UV_INDICEX: 12,
                QUV_INDICEX: 9,
                SIGMA: 100,
                QSIGMA: 9,
                UN: 100,
                QUN: 9,
                HUN: '1230',
                QHUN: 9,
                UX: 100,
                QUX: 9,
                HUX: '1230',
                QHUX: 9,
                UM: 100,
                QUM: 9,
                DHUMI40: 1,
                QDHUMI40: 9,
                DHUMI80: 1,
                QDHUMI80: 9,
                TSVM: 2.2,
                QTSVM: 9,
                ETPMON: 2.2,
                QETPMON: 9,
                ETPGRILLE: 2.2,
                QETPGRILLE: 9,
                ECOULEMENTM: 2.2,
                QECOULEMENTM: 9,
                HNEIGEF: 1,
                QHNEIGEF: 9,
                NEIGETOTX: 1,
                QNEIGETOTX: 9,
                NEIGETOT06: 1,
                QNEIGETOT06: 9,
                NEIG: false,
                QNEIG: 9,
                BROU: false,
                QBROU: 9,
                ORAG: false,
                QORAG: 9,
                GRESIL: false,
                QGRESIL: 9,
                GRELE: false,
                QGRELE: 9,
                ROSEE: false,
                QROSEE: 9,
                VERGLAS: false,
                QVERGLAS: 9,
                SOLNEIGE: false,
                QSOLNEIGE: 9,
                GELEE: false,
                QGELEE: 9,
                FUMEE: false,
                QFUMEE: 9,
                BRUME: false,
                QBRUME: 9,
                ECLAIR: false,
                QECLAIR: 9,
                NB300: 8,
                QNB300: 9,
                BA300: 1,
                QBA300: 9,
                TMERMIN: -3.3,
                QTMERMIN: 9,
                TMERMAX: -3.3,
                QTMERMAX: 9,
            },
            {
                NUM_POSTE: '01014002',
                NOM_USUEL: 'ARBENT',
                LAT: 46.278167,
                LON: 5.669,
                ALTI: 534,
                AAAAMMJJ: new Date('2023-01-03T00:00:00Z'),
                DHUMEC: null,
                QDHUMEC: null,
                PMERM: null,
                QPMERM: null,
                PMERMIN: null,
                QPMERMIN: null,
                INST: null,
                QINST: null,
                GLOT: null,
                QGLOT: null,
                DIFT: null,
                QDIFT: null,
                DIRT: null,
                QDIRT: null,
                INFRART: null,
                QINFRART: null,
                UV: null,
                QUV: null,
                UV_INDICEX: null,
                QUV_INDICEX: null,
                SIGMA: null,
                QSIGMA: null,
                UN: null,
                QUN: null,
                HUN: null,
                QHUN: null,
                UX: null,
                QUX: null,
                HUX: null,
                QHUX: null,
                UM: null,
                QUM: null,
                DHUMI40: null,
                QDHUMI40: null,
                DHUMI80: null,
                QDHUMI80: null,
                TSVM: null,
                QTSVM: null,
                ETPMON: null,
                QETPMON: null,
                ETPGRILLE: null,
                QETPGRILLE: null,
                ECOULEMENTM: null,
                QECOULEMENTM: null,
                HNEIGEF: null,
                QHNEIGEF: null,
                NEIGETOTX: null,
                QNEIGETOTX: null,
                NEIGETOT06: null,
                QNEIGETOT06: null,
                NEIG: null,
                QNEIG: null,
                BROU: null,
                QBROU: null,
                ORAG: null,
                QORAG: null,
                GRESIL: null,
                QGRESIL: null,
                GRELE: null,
                QGRELE: null,
                ROSEE: null,
                QROSEE: null,
                VERGLAS: null,
                QVERGLAS: null,
                SOLNEIGE: null,
                QSOLNEIGE: null,
                GELEE: null,
                QGELEE: null,
                FUMEE: null,
                QFUMEE: null,
                BRUME: null,
                QBRUME: null,
                ECLAIR: null,
                QECLAIR: null,
                NB300: null,
                QNB300: null,
                BA300: null,
                QBA300: null,
                TMERMIN: null,
                QTMERMIN: null,
                TMERMAX: null,
                QTMERMAX: null,
            },
        ]);
    });
});
