-- AlterTable
ALTER TABLE "Horaire"
    ALTER COLUMN "UV" SET DATA TYPE DOUBLE PRECISION,
    ALTER COLUMN "UV2" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "QuotidienneAutresParametres"
    ALTER COLUMN "UV" SET DATA TYPE DOUBLE PRECISION;
